version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5435
    expose:
      - 5435
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    ports:
      - 9999:8000

