"""comment

Revision ID: 6aadb3dcae7c
Revises: 18c255706f8a
Create Date: 2023-11-17 12:07:13.671793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aadb3dcae7c'
down_revision: Union[str, None] = '18c255706f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('yesterday', sa.Float(), nullable=False))
    op.drop_column('rate', 'yesterda')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rate', sa.Column('yesterda', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('rate', 'yesterday')
    # ### end Alembic commands ###
